### ISSUE TITLE
labels on scatterplot

### ISSUE THREAD

**Issue by timvink** [rmnppt/StarWars_textcat#1]
Read your post on http://www.r-bloggers.com/language-categorisation-of-star-wars-character-names/ . I agree the labels are ugly, and thought I'd try the new https://github.com/slowkow/ggrepel package to solve it.

No time to figure out how to submit a pull request, so here is the code:

``` r
library("ggrepel") # devtools::install_github("slowkow/ggrepel")
ggplot(distances, aes(x = x, y = y)) +
  geom_point() +
  geom_text_repel(aes(label = lang), colour = grey(0.5)) # See https://github.com/slowkow/ggrepel
```

**Comment by rmnppt** [comment]
Hi timvink and thank you for reading this and for your suggestion. I edited the script and recompiled the blog. Its still not perfect but a lot better using ggrepel. This package is definitely something I will be playing with in the future!

**Comment by timvink** [comment]
Cool!
